image: "python:3.9"

before_script:
  - python --version
  - curl -sSkL https://install.python-poetry.org | python -
  - export PATH=$PATH:$HOME/.local/bin
  - poetry --version

.install_dev:
  script:
    - poetry install

stages:
  - Static Analysis
  - Security
  - Tests
  - Documentation
  - Release

###################
# Static Analysis #
###################
flake8:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - pip install flake8
    - flake8 .
  needs: []
  only:
    - merge_requests

black:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - pip install black
    - black --check ./
  needs: []
  only:
    - merge_requests

mypy:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - pip install mypy types-setuptools
    - mypy --config-file pyproject.toml .
  needs: []
  only:
    - merge_requests

isort:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - pip install isort
    - isort --check --trailing-comma -m=3 .
  needs: []
  only:
    - merge_requests


############
# Security #
############
bandit:
  stage: Security
  tags:
    - lslab2
  script:
    - pip install bandit
    - bandit -r .
  needs: []
  only:
    - merge_requests


#########
# Tests #
#########
unittests:
  stage: Tests
  tags:
    - lslab2
  script:
    - !reference [.install_dev, script]
    - SDL_VIDEODRIVER=dummy poetry run pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  needs: []
  timeout: 15m
  only:
    - merge_requests

run_game.py:
  stage: Tests
  tags:
    - lslab2
  script:
    - !reference [.install_dev, script]
    - SDL_VIDEODRIVER="dummy" poetry run python run_game.py
  needs: []
  only:
    - merge_requests

coverage:
  stage: Tests
  tags:
  - lslab2
  script:
    - poetry install --with coverage
    - SDL_VIDEODRIVER=dummy poetry run python -m coverage run -m pytest
    - SDL_VIDEODRIVER=dummy poetry run python -m coverage report
    - SDL_VIDEODRIVER=dummy poetry run python -m coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  needs: []
  timeout: 20m
  only:
    - merge_requests
    - main

################
# GitLab Pages #
################
.pages:
  script:
    - poetry install --with docs
    - poetry run sphinx-build -d docs/build/doctrees docs/source docs/build/html
    - mv docs/build/html public/

test-pages:
  stage: Documentation
  tags:
    - lslab2
  extends: .pages
  needs: []
  artifacts:
    expose_as: 'HTML Documentation'
    paths:
      - public/
    expire_in: 1 week
  only:
    - merge_requests

pages:
  stage: Documentation
  tags:
    - lslab2
  extends: .pages
  artifacts:
    paths:
      - public
  only:
    - tags

###########################
# Packaging and Releasing #
###########################
.commit_version:
  script:
    - git remote remove origin
    - git remote add origin https://oauth2:${CI_TAG_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - git config --global user.email "fireline-ci-bot@mitre.org"
    - git config --global user.name "fiReLine CI Bot"
    - git add pyproject.toml
    - git commit -m "Change pyproject.toml version to $VERSION"
    - git push -o ci.skip origin HEAD:main

.check_version_and_commit:
  script:
    - POETRY_VERSION=$(poetry version -s)
    - >
      if [ $POETRY_VERSION != $CI_COMMIT_TAG ]; then
        VERSION=$CI_COMMIT_TAG
        poetry version $VERSION
        git remote remove origin
        git remote add origin https://oauth2:${CI_TAG_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
        git config --global user.email "fireline-ci-bot@mitre.org"
        git config --global user.name "fiReLine CI Bot"
        git add pyproject.toml
        git commit -m "Change pyproject.toml version to $VERSION"
        git push -o ci.skip origin HEAD:main
      fi

test_release:
  stage: Release
  tags:
    - lslab2
  script:
    - poetry build
    - poetry run pip install -U dist/*.whl
    # Remove the directory so that it's not using the directory to run the code and it uses the installed package
    - rm -rf simfire
    - poetry run python tests/package.py
    - poetry run python tests/sim.py
  needs: []
  only:
    - merge_requests

tag:
  stage: Release
  tags:
    - lslab2
  before_script:
    - python --version
    - pip install poetry
    - poetry --version
    - DEBIAN_FRONTEND=noninteractive apt update
    - DEBIAN_FRONTEND=noninteractive apt -y install php php-json git curl
    - git --version
  script:
    - poetry version patch
    - VERSION=$(poetry version -s)
    - LOG=$(git log -1 | grep -Po '(?<=Resolve ")(.*?)(?=")')
    - ISSUE=$(git log -1 | grep -Po '(?<=Closes )(.*?).*')
    - MR=$(git log -1 | grep -Po '(?<=fireline/simfire)(.*?).*')
    - echo -e "# Version ${VERSION}\n\nThis version includes:\n\n* ${LOG} (closed ${ISSUE} with merge request ${MR})" > RELEASE.md
    - MESSAGE="$(php -r "echo json_encode(['name' => '$VERSION', 'tag_name' => '$VERSION', 'description' => file_get_contents('RELEASE.md')]);")"
    - !reference [.commit_version, script]
    - git tag -a $VERSION -m "$VERSION"
    - git push origin $VERSION
    - >
      curl --header 'Content-Type: application/json' \
           --header "PRIVATE-TOKEN: ${CI_TAG_TOKEN}" \
           --data "$MESSAGE" \
           --request POST https://gitlab.mitre.org/api/v4/projects/${CI_PROJECT_ID}/releases
  only:
    - main

release_gitlab:
  stage: Release
  tags:
    - lslab2
  script:
    - !reference [.check_version_and_commit, script]
    - poetry build
    - poetry config repositories.mitre-gitlab https://gitlab.mitre.org/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry publish --repository mitre-gitlab -u gitlab-ci-token -p ${CI_JOB_TOKEN}
  only:
    - tags

release_artifactory:
  stage: Release
  tags:
    - lslab2
  script:
    - !reference [.check_version_and_commit, script]
    - poetry build
    - poetry config repositories.mitre-artifactory https://artifacts.mitre.org/artifactory/api/pypi/python
    - poetry publish --repository mitre-artifactory -u fireline-ci-bot -p ${CI_ARTIFACTORY_TOKEN}
  only:
    - tags
