image: "python:3.9"

before_script:
  - python --version
  - pip install -r dev-requirements.txt

stages:
  - Static Analysis
  - Unit Tests
  - Documentation
  - Release

###################
# Static Analysis #
###################
flake8:
  stage: Static Analysis
  tags:
    - docker
  script:
    - flake8 .
  only:
    - merge_requests

yapf:
  stage: Static Analysis
  tags:
    - docker
  script:
    - if [ `yapf -r ./ -d | wc -l` -gt 0 ] ; then false ; else true ;fi
  only:
    - merge_requests

##############
# Unit Tests #
##############
unittests:
  stage: Unit Tests
  tags:
    - docker
  script:
    - SDL_VIDEODRIVER="dummy" python -m unittest discover -s src -t .. -p "test_*.py"
  only:
    - merge_requests

################
# GitLab Pages #
################
.pages:
  script:
    - pip install -U sphinx sphinx-autoapi sphinx-rtd-theme myst-parser
    - sphinx-build -d docs/build/doctrees docs/source docs/build/html
    - mv docs/build/html public/

test-pages:
  stage: Documentation
  tags:
    - docker
  extends: .pages
  artifacts:
    expose_as: 'HTML Documentation'
    paths:
      - public/
  only:
    - merge_requests

pages:
  stage: Documentation
  tags:
    - docker
    - pages
  extends: .pages
  artifacts:
    paths:
      - public
  only:
    - master

###########################
# Packaging and Releasing #
###########################
test-release:
  stage: Release
  tags:
    - docker
  script:
    - pip install wheel
    - python setup.py bdist_wheel
    - pip install dist/*.whl
  only:
    - master
    - tags

.release:
  script:
    - pip install twine wheel
    - python setup.py bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url https://gitlab.mitre.org/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*

release-dev:
  stage: Release
  tags:
    - docker
  extends: .release
  only:
    - branches

release:
  stage: Release
  tags:
    - docker
  extends: .release
  only:
    - tags
