image: "python:3.9"

before_script:
  - python --version
  - pip install poetry
  - poetry --version
  - poetry install

stages:
  - Static Analysis
  - Tests
  - Documentation
  - Release

###################
# Static Analysis #
###################
flake8:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - poetry run flake8 .
  needs: []
  only:
    - merge_requests

black:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - poetry run black --check ./
  needs: []
  only:
    - merge_requests

mypy:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - poetry run mypy --config-file .mypy.ini .
  needs: []
  only:
    - merge_requests

isort:
  stage: Static Analysis
  tags:
    - lslab2
  script:
    - poetry run isort --check --trailing-comma -m=3 .
  needs: []
  only:
    - merge_requests

#########
# Tests #
#########
unittests:
  stage: Tests
  tags:
    - lslab2
  script:
    # - SDL_VIDEODRIVER=dummy poetry run python -m unittest -v discover -s src -t .. -p 'test_*.py'
    - SDL_VIDEODRIVER=dummy poetry run pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  needs: []
  only:
    - merge_requests

run_game.py:
  stage: Tests
  tags:
    - lslab2
  script:
    - SDL_VIDEODRIVER="dummy" poetry run python run_game.py
  needs: []
  only:
    - merge_requests

coverage:
  stage: Tests
  tags:
  - lslab2
  script:
    - poetry install -E coverage
    - SDL_VIDEODRIVER=dummy poetry run python -m coverage run -m pytest
    - SDL_VIDEODRIVER=dummy poetry run python -m coverage report
    - SDL_VIDEODRIVER=dummy poetry run python -m coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
  needs: []
  only:
    - merge_requests
    - main

################
# GitLab Pages #
################
.pages:
  script:
    - poetry install -E docs
    - poetry run sphinx-build -d docs/build/doctrees docs/source docs/build/html
    - mv docs/build/html public/

test-pages:
  stage: Documentation
  tags:
    - lslab2
  extends: .pages
  needs: []
  artifacts:
    expose_as: 'HTML Documentation'
    paths:
      - public/
    expire_in: 1 week
  only:
    - merge_requests

pages:
  stage: Documentation
  tags:
    - lslab2
    - pages
  extends: .pages
  artifacts:
    paths:
      - public
  only:
    - main

###########################
# Packaging and Releasing #
###########################
test-release:
  stage: Release
  tags:
    - lslab2
  script:
    - poetry build
    - pip install -U dist/*.whl
    - poetry run python tests/package.py
  needs: []
  only:
    - merge_requests

.release:
  script:
    - pip install twine wheel
    - python setup.py bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url https://gitlab.mitre.org/api/v4/projects/${CI_PROJECT_ID}/packages/pypi dist/*

.delete-package:
  script: >
    apt update -y && apt install jq -y

    delete_api_path=$(curl -H "PRIVATE-TOKEN: ${REGISTRY_DELETE_TOKEN}" "https://gitlab.mitre.org/api/v4/projects/${CI_PROJECT_ID}/packages/" | jq -r '.[] | select(.version=="0.0.0") | ._links.delete_api_path')

    curl --request DELETE -H "PRIVATE-TOKEN: ${REGISTRY_DELETE_TOKEN}" "${delete_api_path}"

release-dev:
  stage: Release
  tags:
    - lslab2
  script:
    - !reference [.delete-package, script]
    - !reference [.release, script]
  only:
    - main

release:
  stage: Release
  tags:
    - lslab2
  extends: .release
  only:
    - tags
