# For a description of config parameters, go to
# https://fireline.pages.mitre.org/rothermel-modeling/config.html
area:
  screen_size: 225
  terrain_size: 15
  pixel_scale: 50

display:
  fire_size: 2
  control_line_size: 2

simulation:
  update_rate: 1
  runtime: 24h
  headless: false

mitigation:
  ros_attenuation: true

operational:
  seed:
  latitude: 39.67
  longitude: 119.8
  height: 4000
  width: 4000
  resolution: 30

terrain:
  terrain: operational
  elevation_function: perlin
  perlin:
    amplitude: 500
    shape: (225, 225)
    resolution: (1, 1)
    seed: 1111
  gaussian:
    amplitude: 500
    mu_x: 50
    mu_y: 50
    sigma_x: 50
    sigma_y: 50

fuel:
  fuel: operational
  fuel_array_function: chaparral
  chaparral:
    seed: 1113

fire:
  fire_initial_position: (65, 65)
  max_fire_duration: 4

environment:
  moisture: 0.03

wind:
  wind_function: perlin
  cfd:
    time_to_train: 1000 # Seconds, longer is better
    iterations: 1
    scale: 1
    timestep_dt: 1.0
    diffusion: 0.0
    viscosity: 0.0000001
    speed: 19
    direction: north
  simple:
    speed: 7
    direction: 90.0
  perlin:
    speed:
      seed: 2345
      scale: 400
      octaves: 3
      persistence: 0.7
      lacunarity: 2.0
      min: 7
      max: 47
    direction:
      seed: 650
      scale: 1500
      octaves: 2
      persistence: 0.9
      lacunarity: 1.0
      min: 0.0
      max: 360.0

render:
  inline: true
  post_agent: false
  post_agent_with_fire: false
