# For a description of config parameters, go to
# https://fireline.pages.mitre.org/rothermel-modeling/config.html
area:
  screen_size: 9
  terrain_size: 3
  pixel_scale: 50

display:
  fire_size: 2
  control_line_size: 2

simulation:
  update_rate: 1
  runtime: 24h
  headless: true

mitigation:
  ros_attenuation: true

terrain:
  terrain: functional
  elevation_function: gaussian
  perlin:
    amplitude: 500
    shape: (9, 9)
    resolution: (1, 1)
    seed: 1111
  gaussian:
    amplitude: 500
    mu_x: 50
    mu_y: 50
    sigma_x: 50
    sigma_y: 50

fuel:
  fuel: functional
  fuel_array_function: chaparral
  chaparral:
    seed: 1113

fire:
  fire_initial_position: (5, 3)
  max_fire_duration: 4

environment:
  moisture: 0.03

wind:
  wind_function: perlin
  simple:
    speed: 7
    direction: 90.0
  perlin:
    speed:
      seed: 2345
      scale: 400
      octaves: 3
      persistence: 0.7
      lacunarity: 2.0
      min: 7
      max: 47
    direction:
      seed: 650
      scale: 1500
      octaves: 2
      persistence: 0.9
      lacunarity: 1.0
      min: 0.0
      max: 360.0

render:
  inline: false
  post_agent: false
  post_agent_with_fire: true
